version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./init_backend.sh:/init_backend.sh
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./credentials.json:/app/credentials.json
      - ./client_secret.json:/app/client_secret.json
    entrypoint: sh -c "/init_backend.sh"
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      db: 
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/main
      OAUTHLIB_INSECURE_TRANSPORT: 1

  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 2s
      retries: 5


volumes:
  db-data:
